platform :ios, '9.0'

target 'Final_Project' do
  use_frameworks!

  # UI
  pod 'SVProgressHUD'
  
  # Tool to enforce Swift style and conventions
  pod 'SwiftLint', '0.27.0'

  # Load image
  pod 'SDWebImage', '~> 5.0'

end
